openapi: 3.0.0
info:
  title: membership
  version: '1.0'
  description: Odoo Membership API
  contact:
    name: SuuSoJeat
    email: suusojeat@gmail.com
servers:
  - url: 'http://localhost:3000'
paths:
  /memberships:
    post:
      summary: Create a new membership account
      tags:
        - developer
      responses:
        '201':
          description: Created
      operationId: post-memberships
      description: Creating a new membership account from vKclub app by sending personal information for verification.
      requestBody:
        description: multipart/form-data request body.
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                cardType:
                  type: string
                  enum:
                    - Passport
                    - NationalID
                cardNumber:
                  type: string
                uid:
                  type: string
                  format: uuid
                frontImage:
                  type: string
                  format: binary
                  description: Front image file.
                backImage:
                  type: string
                  format: binary
                  description: Back image file.
                location:
                  type: string
                deviceModel:
                  type: string
                os:
                  type: string
                selfieImage:
                  type: string
                  format: binary
              required:
                - cardType
                - cardNumber
                - uid
                - frontImage
                - backImage
                - selfieImage
      parameters: []
    get:
      summary: Retrieve Membership Data By ID
      operationId: get-memberships
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  registrationStatus:
                    type: string
                  membershipStatus:
                    type: string
                  level:
                    type: integer
                    format: int32
                    minimum: 0
                  totalBalance:
                    type: integer
                    minimum: 0
                  rewardBalance:
                    type: integer
                    minimum: 0
                  willExpireTomorrowBalance:
                    type: integer
                    minimum: 0
                required:
                  - id
                  - name
                  - registrationStatus
                  - membershipStatus
                  - totalBalance
                  - rewardBalance
                  - willExpireTomorrowBalance
      parameters:
        - schema:
            type: string
          in: query
          name: membershipID
          required: true
      security:
        - accessToken: []
      description: Retrieving the membership data by ID after verified PIN code.
      tags:
        - developer
    parameters: []
  /memberships/pin/verifications:
    post:
      summary: Verify Membership PIN Code.
      tags:
        - developer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                required:
                  - accessToken
      operationId: post-memberships-pin-verifications
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                membershipID:
                  type: string
                pinCode:
                  type: string
                uid:
                  type: string
                deviceToken:
                  type: string
                metaInfo:
                  $ref: '#/components/schemas/MetaInfo'
              required:
                - membershipID
                - pinCode
                - uid
                - deviceToken
                - metaInfo
        description: Verify PIN Code from vKclub.
      description: Verify Membership PIN Code for connection and payment.
  /memberships/pin:
    post:
      summary: Update Membership PIN Code
      tags:
        - developer
      responses:
        '200':
          description: OK
      operationId: post-memberships-pin
      description: Change a new PIN Code using the current PIN.
      security:
        - accessToken: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                membershipID:
                  type: string
                uid:
                  type: string
                deviceToken:
                  type: string
                currentPIN:
                  type: string
                newPIN:
                  type: string
                metaInfo:
                  $ref: '#/components/schemas/MetaInfo'
              required:
                - membershipID
                - uid
                - deviceToken
                - currentPIN
                - newPIN
                - metaInfo
        description: Change a new PIN Code from vKclub.
  /memberships/transactions:
    get:
      summary: Listing all transactions of a membership account.
      tags:
        - developer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
      operationId: get-memberships-transactions
      description: 'Listing of all transactions belong to a membership account with the specified {membershipID}'
      security:
        - accessToken: []
      parameters:
        - schema:
            type: string
          in: query
          name: transactionID
          required: true
  /memberships/registrations/info:
    get:
      summary: Get registration info by registrationID
      tags:
        - developer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  registrationStatus:
                    type: string
                  email:
                    type: string
                  phoneNumber:
                    type: string
                  rejectedReason:
                    type: string
      operationId: get-memberships-registrations-info
      description: Retrieve registration info.
      parameters:
        - schema:
            type: string
          in: query
          name: registrationID
          required: true
  /payments/orders:
    get:
      summary: Get order info with orderID.
      tags:
        - developer
      responses: {}
      operationId: get-payments-orders
      description: Retrieve order info from Odoo with an orderID.
      security:
        - accessToken: []
  /memberships/pin/reset:
    post:
      summary: Reset PIN.
      tags:
        - developer
      responses: {}
      operationId: post-memberships-pin-reset
      description: Reset PIN Code when user forget.
      security:
        - accessToken: []
components:
  schemas:
    MetaInfo:
      title: MetaInfo
      type: object
      x-tags:
        - developer
      properties:
        location:
          type: string
        deviceModel:
          type: string
        os:
          type: string
      description: "User's data used for analytics purpose."
    Transaction:
      title: Transaction
      type: object
      x-tags:
        - developer
      description: Model for membership balance transactions.
      properties:
        id:
          type: string
        type:
          type: string
          enum:
            - payment
            - reward
            - allocation
            - top up
        createdAt:
          type: string
          format: date-time
        valuedAt:
          type: string
          format: date-time
        note:
          type: string
        amount:
          type: number
      required:
        - id
        - type
        - createdAt
        - valuedAt
        - amount
  securitySchemes:
    accessToken:
      type: http
      scheme: Bearer
      description: Access Token acquired from PIN code verification.
tags:
  - name: developer
    description: API that will be used by developers/client app.
