openapi: 3.0.0
info:
  title: membership
  version: '1.0'
  description: ''
servers:
  - url: 'http://localhost:3000'
paths:
  /memberships:
    post:
      summary: Create a new membership account
      tags: []
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  registrationID:
                    type: string
                  status:
                    type: string
                required:
                  - registrationID
              examples:
                example-success:
                  value:
                    registrationID: '00001'
                    status: PENDING
      operationId: post-memberships
      description: ''
      requestBody:
        description: ''
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                cardType:
                  type: string
                  enum:
                    - Passport
                    - NationalID
                cardNumber:
                  type: string
                uid:
                  type: string
                  format: uuid
                frontImage:
                  type: string
                  format: binary
                  description: Front image file.
                backImage:
                  type: string
                  format: binary
                  description: Back image file.
                location:
                  type: string
                deviceModel:
                  type: string
                os:
                  type: string
              required:
                - cardType
                - cardNumber
                - uid
                - frontImage
                - backImage
components:
  schemas: {}
